name: "NPM Publish"
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: './.github/actions/setup-node'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Run tests
        run: npm test
      - name: Publish to npm registry
        uses: JS-DevTools/npm-publish@v3
        # https://github.com/marketplace/actions/npm-publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
